language: cpp
sudo: false
os:
  - linux

script:
#  - sudo apt-get install cmake libgtest-dev
  - cmake -H. -Bcmake-build-debug
  - cd cmake-build-debug
  - cmake --build .
  - ./test/native-web-app-test
#  - ctest --output-on-failure

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake


