language: cpp
sudo: false
os:
  - linux

script:
  - cmake -H. -Bcmake-build-debug
  - cd cmake-build-debug
  - cmake --build .
  - ctest --output-on-failure

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake


