language: cpp
sudo: false
os:
- linux

#compiler:
#- clang
#- gcc

matrix:
  include:
  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
- eval "${MATRIX_EVAL}"

script:
#  - sudo apt-get install cmake libgtest-dev
  - cmake -H. -Bcmake-build-debug
  - cd cmake-build-debug
  - cmake --build .
  - ./test/native-web-app-test
#  - ctest --output-on-failure

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - gcc-6
#      - g++-6
#      - cmake
#
#
#